# AppVeyor build configuration
# Author(s):       iFarbod <ifarbod@outlook.com>
#
# Copyright (c) 2015-2017 CTNorth Team
#
# Distributed under the MIT license (See accompanying file LICENSE or copy at
# https://opensource.org/licenses/MIT)

#---------------------------------#
#      General configuration      #
#---------------------------------#
version: '{build}'

branches:
  only:
    - master

skip_tags: false

#---------------------------------#
#    Environment configuration    #
#---------------------------------#
image: Visual Studio 2017

clone_depth: 1

#environment:
  #NSIS_ROOT: $(APPVEYOR_BUILD_FOLDER)\Shared\Installer\NSIS

#cache:
  #- Vendor\cef3 -> Vendor\cef3\temp.tar.bz2

#---------------------------------#
#       Build configuration       #
#---------------------------------#
platform:
  - Win32
  #- x64

configuration: Release

before_build:
  - premake5 vs2017

build:
  parallel: true
  project: Build/DepTest.sln
  verbosity: minimal

#after_build:
  #- utils\premake5 install_data
  #- utils\premake5 compose_files

#---------------------------------#
#       Tests configuration       #
#---------------------------------#
#test_script:
  #- utils\premake5 run_tests

#---------------------------------#
#      Artifacts configuration    #
#---------------------------------#
#artifacts:
  #- path: out\ClTest.exe
    #name: ClTest.exe
  #- path: out\ClTest.pdb
    #name: ClTest.pdb

#---------------------------------#
#     Deployment configuration    #
#---------------------------------#
deploy:
  - provider: GitHub
    release: v$(appveyor_build_version)
    description: 'Release description'
    auth_token:
      secure: 4AFmmvGx92DlQ3DTqXvqBrkTQLynrgNggKRaOo1Y2Fk5x7zAj8bw0MSbpRGqSClV
    artifact: ClTest.exe, ClTest.pdb
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    release: v$(appveyor_build_version)
    description: 'Release description'
    auth_token:
      secure: 4AFmmvGx92DlQ3DTqXvqBrkTQLynrgNggKRaOo1Y2Fk5x7zAj8bw0MSbpRGqSClV
    artifact: ClTest.exe, ClTest.pdb
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false

#---------------------------------#
#         Notifications           #
#---------------------------------#
notifications:
  # GitHub PR comment
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
